### ISSUE TITLE
Same sequence return different embeddings

### ISSUE THREAD

**Issue by dennistamyf** [cran2367/sgt#12]
Thank you for your work. 

I am currently running it on a dataset of around 6million rows, 6 alphabets. However, I get different embeddings even for the same sequence. Is it possible?

I can further supply information later.

Thanks!

**Comment by cran2367** [comment]
Hi Dennis,

Thank you for reaching out. Sgt should not give different embeddings unless
some parameter is changed. Can you give examples?

Thanks,
Chitta

**Comment by dennistamyf** [comment]
Problem has been resolved. It was my own data merging problem not SGT's problem. Closing issue. Thank you!
