### ISSUE TITLE
Question regarding cluster configuration on 1M protein sequences runs on Spark

### ISSUE THREAD

**Issue by SoulEvill** [cran2367/sgt#4]
Hi Chitta Ranjan,

Thanks for making this repository available, it is really helpful! 

I am planning to leverage the repository on 10M dataset but just wondering what cluster configuration you were using for your 1M protein and what's your suggestions on the instances type for sgt. 

Thanks a lot!

**Comment by cran2367** [comment]
@SoulEvill thank you for the note!

I used the following 
https://ibb.co/BNdrbW2
