### ISSUE TITLE
Error when fitting list of integers

### ISSUE THREAD

**Issue by NasirKhalid24** [cran2367/sgt#8]
![Screen Shot 2020-09-20 at 2 40 22 AM](https://user-images.githubusercontent.com/29706203/93690561-b8539c80-faea-11ea-9593-288580fb27d6.png)

**Comment by cran2367** [comment]
@NasirKhalid24 can you replace the integers with strings and try?

**Comment by NasirKhalid24** [comment]
I replaced it with strings and got another error. Instead I replaced each number with a single character and that worked but this might be an issue for some since we are limited by the number of characters usable.
